### ISSUE TITLE
Response 500 Internal Server Error

### ISSUE THREAD

**Issue by umisora** [dito/github-pr-message#13]
Githubに設定して実際に動かした所、Internal Server Errorになったので
調査用にIssueを起こします。

Heroku App Logs
[heroku.log](https://github.com/dito/github-pr-message/files/2122244/heroku.log)

Github Request Header
[request_header.log](https://github.com/dito/github-pr-message/files/2122245/request_header.log)

Github Request Body
[request_body.log](https://github.com/dito/github-pr-message/files/2122246/request_body.log)

**Comment by umisora** [comment]
@dito

**Comment by grezar** [comment]
これなんだっけなー。前起きて直したんだけど

**Comment by dito** [comment]
team の description がないときに発生していた。
e56cc41176752d4fed420753e890e127d732ea3f
で対応しました
